# Generated by Django 3.0.3 on 2020-04-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_auto_20200410_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='positive_transactions', to='accounts.AssetAccount')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='negative_transactions', to='accounts.AssetAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AssetAccount')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.RevenueAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Currency')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ExpenseAccount')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AssetAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
