# Generated by Django 3.0.3 on 2020-04-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_positive_transactions', to='accounts.ExpenseAccount'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_negative_transactions', to='accounts.AssetAccount'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='revenue_positive_transactions', to='accounts.AssetAccount'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='revenue_negative_transactions', to='accounts.RevenueAccount'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_positive_transactions', to='accounts.AssetAccount'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_negative_transactions', to='accounts.AssetAccount'),
        ),
    ]
