# Generated by Django 3.0.3 on 2020-04-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0002_auto_20200410_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category'),
        ),
    ]
