# Generated by Django 3.0.3 on 2020-04-10 16:18

from django.db import migrations


def load_currencies():
    from expenses.config.common import BASE_DIR
    import os
    sql_statements = open(os.path.join(BASE_DIR, 'core/sql/currencies.sql'), 'r').read()
    return sql_statements


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_currencies()),
    ]
